version: '3.2'
services:
  proxy:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./conf.d/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./app:/opt/app
    environment:
      - REDIS_URL=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: 'redis:5.0.7-alpine3.10'
    volumes:
      - redis-data:/var/lib/redis
    ports:
      - "6379:6379"

volumes:
  redis-data:
